import{S as p,i as n}from"./assets/vendor-8c59ed88.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function m(s){return fetch(`https://pixabay.com/api/?key=45377125-53da1a565bd8b37af868a9bcd&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()}).catch(r=>{iziToast.error({position:"topRight",message:`${r.message}`})})}const c=document.querySelector(".gallery-container"),l=document.querySelector(".loader"),g=new p(".gallery-container a",{captions:!0,captionsData:"alt",captionDelay:250});function y(s){const i=s.map(({webformatURL:o,largeImageURL:r,tags:e,likes:t,views:a,comments:h,downloads:f})=>`
        <li class="gallery-item">
        <a href="${r}">
          <img src="${o}" alt="${e}" />
          <div class="statictics">
            <div class = "statictics-text"><h3>Likes</h3><p> ${t}</p></div>
            <div class = "statictics-text"><h3>Views</h3><p>${a}</p></div>
            <div class = "statictics-text"><h3>Comments</h3><p>${h}</p></div>
            <div class = "statictics-text"><h3>Downloads</h3><p>${f}</p></div>
          </div>
        </a></li>`).join("");u(),c.insertAdjacentHTML("beforeend",i),g.refresh()}function L(){const s="";c.innerHTML=s}function v(){l.classList.remove("hidden")}function u(){l.classList.add("hidden")}const d=document.querySelector(".form");d.addEventListener("submit",$);function $(s){s.preventDefault(),v(),L();const i=s.currentTarget.input.value.trim();if(i==="")return n.error({message:"Please enter your search query.",position:"topRight"}),u();m(i).then(o=>{o.hits.length===0&&n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),y(o.hits)}).catch(o=>{n.error({title:"Error",message:o.message})}).finally(()=>{d.reset()})}
//# sourceMappingURL=commonHelpers.js.map
